(Color) =  input("Hi I'm SA55-bot, my master calls me sassy for some reason, nice to meet you. Let's get to know each other. What's your favorite color?")
print ("Wait... Your favorite color is")
print (Color)
input ("(answer yes/no)")
print ("Ooook... look...buddy")
print ("I'm not one to judge or anything but that isn't really the coolest color around")
hobby = input ("anyway, besides that... what do you like to do for fun?")
print ("Really...you like to")
print (hobby) 
input
print ("Ok... you know what, I don't think this is gonna work out. Nice meeting you though... more or less")